name: Build and deploy Python package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: debian-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Setup all dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build package and publish PYPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
